### ISSUE TITLE
Replace basictex with tinytex

### ISSUE THREAD

**Issue by robsalasco** [adamhsparks/setup_macOS_for_R#1]
Hi!

I have been running tinytex (https://yihui.name/tinytex/) several months without any issue and it fits perfect this custom R setup.

Thank you!

**Comment by adamhsparks** [comment]
Nice! Thanks for the tip. I'm vaguely aware of TinyTex but hadn't really looked at it for use. That does seem like it fits this installation nicely.

**Comment by adamhsparks** [comment]
Thanks for the suggestion, @robsalasco, I've tried it on my work computer and updated the README with your suggestion.

https://github.com/adamhsparks/setup_macOS_for_R/commit/ad747c65aa86c8d4fbf18cae04c09685cefcc3c0
